services:
  tracking-sheet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-sheet
    restart: unless-stopped
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NG_ALLOWED_HOSTS=localhost,127.0.0.1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
